@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v4

### Bienvenida
GET {{root}}

### Autoridades
GET {{baseUrl}}/autoridades
    ?size=20
X-Api-Key: {{api_key}}

### Juzgados del Distrito Judicial de Torreon
GET {{baseUrl}}/autoridades
    ?distrito_clave=DTRC
    &es_jurisdiccional=true
    &es_notaria=false
    &size=20
X-Api-Key: {{api_key}}

### ERROR Juzgados del Distrito Judicial de Monterrey
GET {{baseUrl}}/autoridades
    ?distrito_clave=DMTY
    &es_jurisdiccional=true
    &es_notaria=false
    &size=20
X-Api-Key: {{api_key}}

### Notarias del Distrito Judicial de Saltillo
GET {{baseUrl}}/autoridades
    ?distrito_clave=DSLT
    &es_jurisdiccional=true
    &es_notaria=true
    &size=20
    &page=4
X-Api-Key: {{api_key}}

### Juzgado SLT-J1-FAM
GET {{baseUrl}}/autoridades/SLT-J1-FAM
X-Api-Key: {{api_key}}

### Juzgado TRC-J2-CIV
GET {{baseUrl}}/autoridades/TRC-J2-CIV
X-Api-Key: {{api_key}}
