@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Listas de Acuerdos
GET {{baseUrl}}/listas_de_acuerdos/pages
X-Api-Key: {{api_key}}

### Listas de Acuerdos
GET {{baseUrl}}/listas_de_acuerdos/limit-offset
X-Api-Key: {{api_key}}
