@api_key = {{$dotenv API_KEY}}
@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v3

### Bienvenida
GET {{root}}

### Listas de Acuerdos
GET {{baseUrl}}/listas_de_acuerdos
X-Api-Key: {{api_key}}

### Listas de Acuerdos del Distrito Judicial de Torreon
GET {{baseUrl}}/listas_de_acuerdos
    ?distrito_clave=DTRC
X-Api-Key: {{api_key}}

### Listas de Acuerdos del SLT-J2-CIV
GET {{baseUrl}}/listas_de_acuerdos
    ?autoridad_clave=SLT-J2-CIV
X-Api-Key: {{api_key}}

### Listas de Acuerdos del 2023-07-10
GET {{baseUrl}}/listas_de_acuerdos
    ?fecha=2023-07-10
X-Api-Key: {{api_key}}

### ERROR Listas de Acuerdos del SLT-J8-CIV
GET {{baseUrl}}/listas_de_acuerdos
    ?autoridad_clave=SLT-J8-CIV
X-Api-Key: {{api_key}}

### Una lista de acuerdos por su ID
GET {{baseUrl}}/listas_de_acuerdos/118195
X-Api-Key: {{api_key}}

### ERROR Una lista de acuerdos por su ID
GET {{baseUrl}}/listas_de_acuerdos/999999
X-Api-Key: {{api_key}}
